## Add tool(s)

In [1]:
%matplotlib inline
import pandas as pd
import numpy as np

In [2]:
data = pd.read_excel('120s PDM Data.xlsx',sheet_name = None)

In [3]:
xls = pd.ExcelFile('120s PDM Data.xlsx')
xls.sheet_names 
flow = data.get('Flow')
flow.head()

,TRAVELER,TRAV DESC,STEP NAME,RECIPE NAME,WS,AREA,RPT MINS,WS LOAD PCT,DISPATCH RPT,SUBSET,...,SUB-FAMILY,PROCESS,DENSITY,RPT VALIDATION STATUS,MODELED UTIL,AVG LOADSIZE,MODELED AVAIL,LOST TIME,RPT BASIS,MODELED CHAMBERS
0,V00H,100S PC,0000-00 START LOT START,PC LOT START,11-3START_WAFERS,F11 GENERAL,0.43,100.0,NaN,_,...,DDR III,D100S,4 GIG,NaN,1.00,25.0,1.00,0.0,NaN,1.0
1,V00H,100S PC,5450-21 STI OXIDE BACKSIDE WET ETCH,WET_100S_SWC_DHF100,11-3DNS_SU31_DHF_4,F11 WET PROCESS,0.70,0.0,NaN,_,...,DDR III,D100S,4 GIG,NaN,0.88,1.0,0.96,0.0,NaN,1.0
2,V00H,100S PC,5450-21 STI OXIDE BACKSIDE WET ETCH,WET_100S_SWC_DHF100,11-3DNS_SU3_DHF100,F11 WET PROCESS,0.70,5.0,NaN,_,...,DDR III,D100S,4 GIG,NaN,0.88,1.0,0.96,0.0,NaN,1.0
3,V00H,100S PC,5450-21 STI OXIDE BACKSIDE WET ETCH,WET_100S_SWC_DHF100,11-3DNS_SU31_DHF100,F11 WET PROCESS,0.35,95.0,NaN,_,...,DDR III,D100S,4 GIG,NaN,0.88,1.0,0.96,0.0,NaN,1.0
4,V00H,100S PC,5200-53 GATE NITRIDE DEP 2 CMP,CMP_100S_BUFF,11-3EBRA_FRXS_BUFF,F11 CMP,1.12,100.0,NaN,_,...,DDR III,D100S,4 GIG,NaN,0.75,1.0,0.86,0.0,1.0,1.0

In [4]:
process = input('Please Enter the product: ')

Please Enter the product: 120S PC

#### choose product

In [5]:
flow = flow[flow['TRAV DESC'] == process]
flow.shape[0]

6326

In [6]:
flow = flow[flow.AREA != 'F11 GENERAL']
step = flow['WS'][:-1].tolist()
#print(step)
flow.head()

,TRAVELER,TRAV DESC,STEP NAME,RECIPE NAME,WS,AREA,RPT MINS,WS LOAD PCT,DISPATCH RPT,SUBSET,...,SUB-FAMILY,PROCESS,DENSITY,RPT VALIDATION STATUS,MODELED UTIL,AVG LOADSIZE,MODELED AVAIL,LOST TIME,RPT BASIS,MODELED CHAMBERS
11027,Y21H,120S PC,5200-53 GATE NITRIDE BUFF CMP,CMP_120S_BUFF,11-3EBRA_FRXS_BUFF1,F11 CMP,1.21,100.0,NaN,_,...,GDDR6,D120S,8 GIG,NaN,0.75,1.0,0.85,0.0,NaN,1.0
11029,Y21H,120S PC,4800-00 PAD OXIDATION,DIF_THOX,11-3TEL_303I_PADOX,F11 DIFFUSION,130.50,100.0,NaN,_,...,GDDR6,D120S,8 GIG,NaN,0.76,100.0,0.95,0.0,NaN,1.0
11030,Y21H,120S PC,1230-00 PAD OXIDATION THK,METRO_120S_THK,11-3KLAT_FX200_THK,F11 METROLOGY,2.00,8.0,NaN,_,...,GDDR6,D120S,8 GIG,NaN,0.40,24.0,0.95,0.0,NaN,1.0
11031,Y21H,120S PC,1230-00 PAD OXIDATION THK,METRO_120S_THK,11-3KLAT_F5X_THK,F11 METROLOGY,2.00,8.0,NaN,_,...,GDDR6,D120S,8 GIG,NaN,0.40,24.0,0.95,0.0,1.0,1.0
11032,Y21H,120S PC,1230-00 PAD OXIDATION THK,METRO_120S_THK,11-3KLAT_FX100_THK,F11 METROLOGY,2.00,8.0,NaN,_,...,GDDR6,D120S,8 GIG,NaN,0.40,24.0,0.95,0.0,NaN,1.0

In [7]:
Qty = data.get('Qty')

In [8]:
WS_EQ = pd.concat([Qty['WS NAME'],Qty['EQUIP ID']],axis=1)
WS_EQ.head() #機台對應 WS
WS_NAME = WS_EQ['WS NAME'].tolist()
#print(WS_NAME)

In [9]:
WS_EQ.head()

            WS NAME    EQUIP ID
0  11-3ABON_ZFB_N2P  AN2PB80101
1  11-3ABON_ZFB_N2P  AN2PB80102
2  11-3ABON_ZFB_N2P  AN2PB80103
3  11-3ABON_ZFB_N2P  AN2PB80104
4  11-3ABON_ZFB_N2P  AN2PB80105

In [19]:
wafer = input('Please enter the quantity of wafers:')
wafer_m = []
for i in step:
    if i in WS_NAME:
        w = round(int(wafer)/WS_EQ.groupby(['WS NAME']).size()[i],2)
        wafer_m.append(w)
    else:
        wafer_m.append(0)
    #print(i)
#print ('Number of wafers in each machine:',wafer_m)

Please enter the quantity of wafers:600

In [31]:
add_WS = input('Please enter the WS to add tool : ') #增加機台的 Workstation
included_WS = [i for i,x in enumerate(step) if x==add_WS] #重複項索引值
print((included_WS))
#add_machine = input('Please enter the quantity of equipment added: ')
#change_data = wafer_in_each_machine.iloc[int(change_step)-1:int(change_step)+2,] #提取該步驟
change_WS = []
for i in included_WS:
    _WS_ = step[i-1:i+2] #提取索引
    change_WS.append(_WS_)
#print(change_WS)

Please enter the WS to add tool : 11-3CANON_ES5_248
[103, 738, 956, 1016, 1232, 1421, 1755, 1936, 1965, 1994, 2031, 2120, 2258, 2313, 2344, 3035, 3231, 3736, 4736, 4910, 4998]

In [24]:
col = ['3','4','7','8','9','C','D','E']
#print(wafer_in_each_machine)
wafer_in_each_machine = pd.DataFrame(columns = col)
machine_num = pd.DataFrame(columns = col)
for i in change_WS:
    for j in range(3):
        f1 = WS_EQ[(WS_EQ['WS NAME'] == i[j]) & (WS_EQ['EQUIP ID'].str.get(5) == '3')].shape[0]
        f2 = WS_EQ[(WS_EQ['WS NAME'] == i[j]) & (WS_EQ['EQUIP ID'].str.get(5) == '4')].shape[0]
        f3 = WS_EQ[(WS_EQ['WS NAME'] == i[j]) & (WS_EQ['EQUIP ID'].str.get(5) == '7')].shape[0]
        f4 = WS_EQ[(WS_EQ['WS NAME'] == i[j]) & (WS_EQ['EQUIP ID'].str.get(5) == '8')].shape[0]
        f5 = WS_EQ[(WS_EQ['WS NAME'] == i[j]) & (WS_EQ['EQUIP ID'].str.get(5) == '9')].shape[0]
        f6 = WS_EQ[(WS_EQ['WS NAME'] == i[j]) & (WS_EQ['EQUIP ID'].str.get(5) == 'C')].shape[0]
        f7 = WS_EQ[(WS_EQ['WS NAME'] == i[j]) & (WS_EQ['EQUIP ID'].str.get(5) == 'D')].shape[0]
        f8 = WS_EQ[(WS_EQ['WS NAME'] == i[j]) & (WS_EQ['EQUIP ID'].str.get(5) == 'E')].shape[0]
        machine = np.array([f1,f2,f3,f4,f5,f6,f7,f8])
        machine_D = pd.DataFrame([machine],columns = col)
        machine_num = machine_num.append(machine_D)
        
        for k in range(8):
            if i[j] in WS_NAME:
                num = wafer_m[step.index(i[j])]*machine[k]
            else:
                num = 0
            machine[k] = num
        machine = pd.DataFrame([machine],columns = col)
        #print(machine)
        wafer_in_each_machine = wafer_in_each_machine.append(machine)
wafer_in_each_machine.head()
print(wafer_in_each_machine.shape[0])

63

In [13]:
df = pd.DataFrame()
for i in range(8):
    for j in range(1,len(included_WS)*3,3):
        machine_num.values[j,i] =  machine_num.values[j,i]+1
        wafer_in_each_machine.values[j] = machine_num.values[j]*(int(wafer)/(sum(machine_num.values[j])))
        machine_num.values[j,i] =  machine_num.values[j,i]-1
    df = pd.concat([df,wafer_in_each_machine],axis = 0)
    #print (wafer_in_each_machine)
    #print ('=============================')
df.head()

     3  4    7  8  9    C  D  E
0    0  0  599  0  0    0  0  0
0  150  0  450  0  0    0  0  0
0  600  0    0  0  0    0  0  0
0    0  0  200  0  0  400  0  0
0  150  0  450  0  0    0  0  0

In [91]:
data = np.vsplit(df.values, len(change_WS)*len(col))

def weight(distance,carry):
    total_carry = []
    for i in range(2):
        carry_weight = np.multiply(carry[i],distance)
        total_carry_step = np.sum(carry_weight)-np.trace(carry_weight) 
        total_carry.append(total_carry_step)
    return sum(total_carry)

Carriage = []
for l in range(len(change_WS)*len(col)):
    a = range(len(col))
    c_m = []
    for k in range(2):
        for j in a:
            for i in a:
                c_n = max(data[l][k,j]-data[l][k+1,j],0)*data[l][k+1,a]//(int(wafer)-data[l][k+1,j]+1) #避免分母為零
            c_m.append(c_n)      
    c_step_m = np.array(c_m)
    #print(c_step_m)
    #print(c_step_m.shape)
    c_carry = np.vsplit(c_step_m, 2)
    for i in range(2):
        for j in range(8):
            c_carry[i][j][j] = min(data[l][i,j],data[l][i+1,j])
            c_carry = np.array(c_carry)
    Carriage.append(weight(distance = np.ones((8,8)),carry = c_carry))
Carriage = np.array([Carriage]).reshape(len(change_WS),8)
Carriage = pd.DataFrame(Carriage,columns = col)
Carriage.head(len(change_WS)+1)

         3       4       7       8       9       C       D       E
0    597.0   847.0  1047.0   673.0  1045.0   747.0   847.0   996.0
1    927.0   598.0   847.0   598.0  1045.0   696.0   747.0   958.0
2    847.0   847.0   673.0   673.0   598.0   746.0   996.0  1196.0
3    896.0  1194.0   994.0   996.0   996.0  1076.0   598.0   996.0
4    598.0  1194.0   994.0   747.0  1107.0   996.0   847.0   896.0
5    896.0   747.0   599.0   998.0  1198.0   897.0  1196.0   997.0
6    998.0   998.0  1078.0   599.0   998.0   599.0  1196.0   997.0
7    599.0  1108.0   998.0   848.0   897.0   897.0   599.0   746.0
8    996.0  1196.0   896.0  1194.0   994.0   996.0   996.0  1076.0
9    598.0   996.0   598.0  1194.0   994.0   747.0  1107.0   996.0
10   847.0   896.0   896.0   747.0   746.0   996.0  1196.0   896.0
11  1194.0   994.0   996.0   996.0  1076.0   598.0   996.0   598.0
12  1194.0   994.0   747.0  1023.0   996.0   847.0   896.0   896.0
13   747.0   746.0   847.0  1047.0   746.0   896.0   845.0   847.0
14   698.0   927.0   449.0   847.0   449.0   896.0   845.0   598.0
15  1107.0   847.0   548.0   746.0   746.0   747.0   746.0   996.0
16  1196.0   896.0  1045.0   994.0   996.0   996.0  1076.0   598.0
17   996.0   598.0  1045.0   994.0   747.0   957.0   996.0   847.0
18   896.0   896.0   747.0   746.0   996.0  1196.0   896.0  1194.0
19   994.0   996.0   996.0  1076.0   598.0   996.0   598.0  1194.0
20   994.0   747.0  1023.0   996.0   847.0   896.0   896.0   747.0

In [100]:
excel = pd.read_excel('flow.xlsx',sheet_name = None)
xls1 = pd.ExcelFile('flow.xlsx')
xls1.sheet_names
compare = excel.get('Sheet1')
compare = compare['Step carriage'].tolist()
b = [i-1 for i in included_WS]
origin = included_WS+b
origin = sorted(origin)
origin_carriage = []
for i in range(0,len(origin)-1,2):
    origin_carriage.append(compare[origin[i]] + compare[origin[i+1]])
origin_carriage = pd.DataFrame(origin_carriage)
Carriage['Original Carriage'] = origin_carriage
Carriage.loc['Total Carriage'] = Carriage.apply(lambda x: x.sum())
Carriage.head(len(change_WS)+1)

,3,4,7,8,9,C,D,E,Original Carriage
0,597.0,847.0,1047.0,673.0,1045.0,747.0,847.0,996.0,599.0
1,927.0,598.0,847.0,598.0,1045.0,696.0,747.0,958.0,998.0
2,847.0,847.0,673.0,673.0,598.0,746.0,996.0,1196.0,1198.0
3,896.0,1194.0,994.0,996.0,996.0,1076.0,598.0,996.0,897.0
4,598.0,1194.0,994.0,747.0,1107.0,996.0,847.0,896.0,1196.0
5,896.0,747.0,599.0,998.0,1198.0,897.0,1196.0,997.0,997.0
6,998.0,998.0,1078.0,599.0,998.0,599.0,1196.0,997.0,998.0
7,599.0,1108.0,998.0,848.0,897.0,897.0,599.0,746.0,998.0
8,996.0,1196.0,896.0,1194.0,994.0,996.0,996.0,1076.0,1078.0
9,598.0,996.0,598.0,1194.0,994.0,747.0,1107.0,996.0,599.0
10,847.0,896.0,896.0,747.0,746.0,996.0,1196.0,896.0,998.0
11,1194.0,994.0,996.0,996.0,1076.0,598.0,996.0,598.0,599.0
12,1194.0,994.0,747.0,1023.0,996.0,847.0,896.0,896.0,1196.0
13,747.0,746.0,847.0,1047.0,746.0,896.0,845.0,847.0,997.0
14,698.0,927.0,449.0,847.0,449.0,896.0,845.0,598.0,599.0
15,1107.0,847.0,548.0,746.0,746.0,747.0,746.0,996.0,1108.0
16,1196.0,896.0,1045.0,994.0,996.0,996.0,1076.0,598.0,998.0
17,996.0,598.0,1045.0,994.0,747.0,957.0,996.0,847.0,848.0
18,896.0,896.0,747.0,746.0,996.0,1196.0,896.0,1194.0,897.0
19,994.0,996.0,996.0,1076.0,598.0,996.0,598.0,1194.0,897.0
20,994.0,747.0,1023.0,996.0,847.0,896.0,896.0,747.0,599.0
Total Carriage,37630.0,38524.0,36126.0,37464.0,37630.0,36836.0,38230.0,38530.0,19294.0